import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClientProvider } from "@tanstack/react-query";

// Auto-generated by TanStack Router Vite plugin — do not edit manually
// It is regenerated on every `vite dev` start
import { routeTree } from "./routeTree.gen";

import { queryClient } from "./lib/query-client";
import "./styles/globals.css";

const router = createRouter({
  routeTree,
  // Provide queryClient in router context so route loaders can prefetch
  context: { queryClient },
});

// Register router type for end-to-end type safety
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById("root");
if (!rootElement) throw new Error("Root element not found");

createRoot(rootElement).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>
);
