"""add_plaid_raw_metadata_to_transactions

Revision ID: 43ee040327ae
Revises: f01_plaid_bank_sync
Create Date: 2026-06-03 12:51:33.924082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43ee040327ae'
down_revision: Union[str, Sequence[str], None] = 'f01_plaid_bank_sync'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('plaid_raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'plaid_raw_metadata')
    # ### end Alembic commands ###
