"""add statements tables

Revision ID: 719a9979bbad
Revises: dbc27ece60ce
Create Date: 2026-05-30 22:08:25.845567

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "719a9979bbad"
down_revision: str | Sequence[str] | None = "dbc27ece60ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issuer_schemas",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("issuer_name", sa.String(length=100), nullable=False),
        sa.Column(
            "file_format",
            sa.Enum("pdf", "csv", name="fileformat"),
            nullable=False,
        ),
        sa.Column("column_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("column_mapping", sa.JSON(), nullable=True),
        sa.Column("raw_headers", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_issuer_schemas_column_fingerprint"),
        "issuer_schemas",
        ["column_fingerprint"],
        unique=False,
    )
    op.create_table(
        "statements",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=True),
        sa.Column("bank_account_id", sa.Uuid(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("issuer_schema_id", sa.Uuid(), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("file_storage_path", sa.String(length=500), nullable=False),
        sa.Column("file_mime", sa.String(length=100), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_original_name", sa.String(length=255), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "parsing",
                "categorizing",
                "needs_review",
                "ready",
                "failed",
                name="statementstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "failure_reason",
            sa.Enum(
                "unreadable_pdf",
                "encrypted",
                "unsupported_format",
                "parsing_error",
                "ai_unavailable",
                name="failurereason",
            ),
            nullable=True,
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_cost_cents", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_account_id"], ["bank_accounts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["household_id"], ["households.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["issuer_schema_id"], ["issuer_schemas.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statements_bank_account_id"),
        "statements",
        ["bank_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statements_card_id"),
        "statements",
        ["card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statements_file_hash"),
        "statements",
        ["file_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statements_household_id"),
        "statements",
        ["household_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_statements_household_id"), table_name="statements")
    op.drop_index(op.f("ix_statements_file_hash"), table_name="statements")
    op.drop_index(op.f("ix_statements_card_id"), table_name="statements")
    op.drop_index(op.f("ix_statements_bank_account_id"), table_name="statements")
    op.drop_table("statements")
    op.drop_index(
        op.f("ix_issuer_schemas_column_fingerprint"),
        table_name="issuer_schemas",
    )
    op.drop_table("issuer_schemas")
    # ### end Alembic commands ###
