"""add_cards_table

Revision ID: 90a7ec3513db
Revises: bda563171b0e
Create Date: 2026-05-29 12:58:21.390998

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90a7ec3513db'
down_revision: str | Sequence[str] | None = 'bda563171b0e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column(
        'id', sa.Uuid(),
        server_default=sa.text('gen_random_uuid()'), nullable=False,
    ),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=100), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column(
        'network',
        sa.Enum('visa', 'mastercard', 'amex', 'discover', 'other', name='cardnetwork'),
        nullable=True,
    ),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('statement_close_day', sa.Integer(), nullable=False),
    sa.Column('payment_due_day', sa.Integer(), nullable=False),
    sa.Column('minimum_payment_cents', sa.Integer(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_cards_household_id'), 'cards', ['household_id'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_household_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
