"""add subscriptions and subscription_charges

Revision ID: afa98176b368
Revises: 0e5d999b6cc3
Create Date: 2026-07-02 15:00:31.842845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa98176b368'
down_revision: Union[str, Sequence[str], None] = '0e5d999b6cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_clean', sa.String(length=500), nullable=False),
    sa.Column('amount_typical', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'monthly', 'quarterly', 'yearly', name='subscriptionfrequency'), nullable=False),
    sa.Column('anchor_day', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'active', 'paused', 'cancelled', 'dismissed', name='subscriptionstatus'), nullable=False),
    sa.Column('next_expected_charge_date', sa.Date(), nullable=True),
    sa.Column('first_seen_at', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.Enum('detected', 'manual', name='subscriptionsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_household_status', 'subscriptions', ['household_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_household_id'), 'subscriptions', ['household_id'], unique=False)
    op.create_table('subscription_charges',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deviation_from_typical', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='uq_subscription_charges_transaction')
    )
    op.create_index('idx_subscription_charges_subscription_id', 'subscription_charges', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subscription_charges_subscription_id', table_name='subscription_charges')
    op.drop_table('subscription_charges')
    op.drop_index(op.f('ix_subscriptions_household_id'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_household_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
