"""add bank accounts table

Revision ID: dbc27ece60ce
Revises: 90a7ec3513db
Create Date: 2026-05-30 19:01:52.626314

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dbc27ece60ce'
down_revision: str | Sequence[str] | None = '90a7ec3513db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bank_accounts',
        sa.Column(
            'id',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column('household_id', sa.Uuid(), nullable=False),
        sa.Column('nickname', sa.String(length=100), nullable=False),
        sa.Column('institution', sa.String(length=100), nullable=False),
        sa.Column(
            'account_type',
            sa.Enum(
                'checking', 'savings', 'money_market', 'other',
                name='accounttype',
            ),
            nullable=False,
        ),
        sa.Column('last4', sa.String(length=4), nullable=True),
        sa.Column('color', sa.String(length=20), nullable=True),
        sa.Column('icon', sa.String(length=50), nullable=True),
        sa.Column('is_shared', sa.Boolean(), nullable=False),
        sa.Column('is_archived', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['household_id'], ['households.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_bank_accounts_household_id'),
        'bank_accounts',
        ['household_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_bank_accounts_household_id'), table_name='bank_accounts'
    )
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
